version: '4'
services:
  postgres-user:
    image: postgres:16.6
    container_name: postgres-produto
    environment:
      POSTGRES_USER: rod
      POSTGRES_PASSWORD: password
      POSTGRES_DB: produto_service
    ports:
      - "5432:5432"
    volumes:
      # Monta o arquivo init.sql para inicialização do banco
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      # Volume para os dados do banco de dados.
      - postgres-data:/var/lib/postgresql/data

# Definindo o volume Docker para os dados
volumes:
  postgres-data:
