version: '4'
services:
  mongo_produto:
    image: mongo:latest
    container_name: mongo_produto
    environment:
      MONGO_INITDB_ROOT_USERNAME: produto
      MONGO_INITDB_ROOT_PASSWORD: produto
      MONGO_INITDB_DATABASE: produtodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: